#!/usr/bin/env bash
# Vendor the platform's PURE logic into this standalone edge project so it stays
# self-contained (buildable without the rest of the monorepo) while never
# duplicating logic by hand. The single source of truth lives in libs/; this copy
# is committed and checked for drift in CI (see the check at the bottom of README).
#
# Run from anywhere; paths are resolved relative to this script.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd "$PROJECT_DIR/../../.." && pwd)"

VENDOR_DIR="$PROJECT_DIR/src/vendor"
SRC_EVALUATOR="$REPO_ROOT/libs/rules-evaluator/src"
SRC_PROTOCOLS="$REPO_ROOT/libs/models/src/device/protocols"

if [[ ! -d "$SRC_EVALUATOR" || ! -d "$SRC_PROTOCOLS" ]]; then
  # Outside the monorepo (e.g. a Docker build whose context is only this project):
  # the committed src/vendor is the source. Skip re-vendoring instead of failing.
  echo "note: monorepo libs not found; using committed src/vendor as-is." >&2
  exit 0
fi

rm -rf "$VENDOR_DIR/rules-evaluator" "$VENDOR_DIR/protocols"
mkdir -p "$VENDOR_DIR/rules-evaluator" "$VENDOR_DIR/protocols"

# Copy sources, excluding test specs.
copy_ts() {
  local src="$1" dst="$2"
  ( cd "$src" && find . -name '*.ts' ! -name '*.spec.ts' -print0 \
    | while IFS= read -r -d '' f; do
        mkdir -p "$dst/$(dirname "$f")"
        cp "$src/$f" "$dst/$f"
      done )
}

copy_ts "$SRC_EVALUATOR" "$VENDOR_DIR/rules-evaluator"
copy_ts "$SRC_PROTOCOLS" "$VENDOR_DIR/protocols"

cat > "$VENDOR_DIR/README.md" <<'EOF'
# Vendored code — DO NOT EDIT

Generated by `scripts/vendor-libs.sh`. Source of truth:
- `libs/rules-evaluator/src` → `rules-evaluator/`
- `libs/models/src/device/protocols` → `protocols/`

Edit the originals in the monorepo, then re-run the script. CI fails if this
directory drifts from the source (`git diff --exit-code src/vendor`).
EOF

echo "vendored rules-evaluator + protocols into src/vendor/"
